title: Jeremy Z Yang
tagline: Assistant Professor at Harvard Business School
logo: /assets/img/new profile.png
description: Assistant Professor at Harvard Business School
Yoshow_downloads: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
